<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>HamePub Lint</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }
            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            .container{
                text-align: left;
                margin: 0 auto;
                padding: 10px;
                max-width: 400px;
            }
            .no-version{

            }
        </style>
    </head>
    <body>
        <h1>HamePub Lint</h1>
        <div>Online ePubCheck Runner</div>

        <div class="container">
            <?php if ($versions) : ?>
                <ul>
                    <?php foreach ($versions as $version) : ?>
                        <li>
                            Version <?= htmlspecialchars($version) ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else : ?>
                <p class="no-version">
                    No versions available!
                </p>
            <?php endif; ?>
        </div>
    </body>
</html>
